# Generated by Django 3.2.7 on 2024-08-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='docker_image',
            field=models.CharField(default='default_image', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='entry_point',
            field=models.CharField(default='default_entry_point', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='port',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='default_slug', unique=True),
            preserve_default=False,
        ),
    ]
